builds:
  - include:
      - "*.x86_64-linux.*"
      - "nixosConfigurations.*"
    branch:
      - main

  - include:
      - "checks.*.*"
    exclude:
      - "*.x86_64-linux.*"
      - "nixosConfigurations.*"
    branch:
      - update_flake_lock_action
