keys:
  - &anisp_cutie age183wu4fhfkl7z8k37v5enfcpca24wwtw6m7c4kzgeks9tecgqesuqasuc9x
  - &anisp_root age1c2f5mtxdvgq5ez3rrntj9lr9j60equwzdzq2xswxcr7kvl5xcgcsl96t3f
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *anisp_cutie
          - *anisp_root
